# DuckCartUtility's configuration file

# Enable the plugin.
plugin-enabled: true
# If minecarts are dropped on the ground when exiting them.
drop-cart-on-exit: true
# Disallow everything except players from entering Minecart.
deny-cart-entry-to-non-player: true
# Any Monster or Animal (except wolves & ocelots) colliding with a cart will be removed.
remove-livingentity-on-cart-collide: true
# Sign control configuration.
sign-control:
  # Enable the whole sign-control feature.
  enabled: true
  # Eject sign
  eject-sign:
    # Enable eject sign.
    enabled: true
    # Maximum distance a player can be ejected. Attempts to go further are normalized.
    max-distance: 20.0
    # If empty minecarts are ejected.
    eject-empty-cart: true
    # If storagecarts are ejected.
    eject-storage-cart: false
# minecart customizer wand
wand:
  enabled: true
  wand-set: true
  # Warning, Data wand is untested, potentially unsafe
  wand-data: false
  wand-offset: true
  wand-toggle: true
  wand-reset: true
  wand-info: true
# allow customization of non-standard minecarts
allow-special-carts-customization: false
