# DuckCartUtility's configuration file

# Enable or Disable the plugin
plugin-enabled: true
# Set if the minecart is dropped on the ground when exiting it.
drop-cart-on-exit: true
# Any Monster or Animal (Except Wolves & Ocelots) colliding with a cart will be removed.
remove-livingentity-on-cart-collide: true
#
sign-control:
  enabled: true
  eject-sign:
    enabled: true
    max-distance: 20.0